services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: workup-frontend-tunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${FRONTEND_CLOUDFLARE_TOKEN}
    command: >
      tunnel --no-autoupdate run
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: workup-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static_files:/usr/share/nginx/html:ro
    

  alloy:
      image: grafana/alloy:latest
      container_name: workup-frontend-alloy
      restart: unless-stopped
      volumes:
        - ./alloy-config.river:/etc/alloy/config.alloy:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/log/audit:/var/log/audit:ro
        - /var/log/journal:/var/log/journal:ro
        - /run/log/journal:/run/log/journal:ro
        - /etc/machine-id:/etc/machine-id:ro
        - /var/log/aide:/var/log/aide:ro
      command: run /etc/alloy/config.alloy
      environment:
        CF_ACCESS_CLIENT_ID: ${CF_ACCESS_CLIENT_ID}
        CF_ACCESS_CLIENT_SECRET: ${CF_ACCESS_CLIENT_SECRET}
      depends_on:
        - nginx