---

stages:
  - test
  - build
  - scan

variables:
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  SAST_EXCLUDED_ANALYZERS: "brakeman,flawfinder,nodejs-scan,phpcs-security-audit,pmd-apex,security-code-scan,sobelow,spotbugs"


default:
  interruptible: true

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


semgrep-sast:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

secret_detection:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

govulncheck:
  stage: test
  image: golang:1.27
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cd app/backend
    - go install golang.org/x/vuln/cmd/govulncheck@latest
    - govulncheck ./...
  allow_failure: true

build-backend:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: "/certs/client"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo "Building backend image..."
    - |
      docker build \
        --tag "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA" \
        --tag "$BACKEND_IMAGE:latest" \
        -f app/backend/Dockerfile \
        app/backend

    - echo "Pushing images to GitLab Container Registry..."
    - docker push "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$BACKEND_IMAGE:latest"

  # Only run this job on the main branch for now
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

trivy-container:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - build-backend
  variables:
    TRIVY_USERNAME: $CI_REGISTRY_USER
    TRIVY_PASSWORD: $CI_REGISTRY_PASSWORD
  script:
    - trivy --version
    - |
      trivy image \
        --severity HIGH,CRITICAL \
        --format json \
        --output gl-container-scanning-report.json \
        "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA"
    - |
      trivy image \
        --severity HIGH,CRITICAL \
        --exit-code 0 \
        "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA"
  artifacts:
    when: always
    paths:
      - gl-container-scanning-report.json
    expire_in: 30 days
  allow_failure: true