services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: workup-auth-tunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${AUTH_CLOUDFLARE_TOKEN}
    command: >
      tunnel --no-autoupdate run

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.2
    container_name: workup-keycloak
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: auth.victorojeje.xyz
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_METRICS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_EVENT_METRICS_USER_EVENTS: "login,logout,register,code_to_token,refresh_token" 
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    

  postgres:
    image: postgres:18-alpine
    container_name: workup-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USERNAME} -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
      image: grafana/alloy:latest
      container_name: workup-auth-alloy
      restart: unless-stopped
      volumes:
        - ./alloy-config.river:/etc/alloy/config.alloy:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/log/audit:/var/log/audit:ro
        - /var/log/journal:/var/log/journal:ro
        - /run/log/journal:/run/log/journal:ro
        - /etc/machine-id:/etc/machine-id:ro
      command: run /etc/alloy/config.alloy
      environment:
        CF_ACCESS_CLIENT_ID: ${CF_ACCESS_CLIENT_ID}
        CF_ACCESS_CLIENT_SECRET: ${CF_ACCESS_CLIENT_SECRET}
      depends_on:
        - keycloak

volumes:
  postgres-data:
