services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: workup-api-tunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${API_CLOUDFLARE_TOKEN}
    command: >
      tunnel --no-autoupdate run
    depends_on:
      postgres:
        condition: service_healthy

  
  api:
    image: registry.gitlab.com/ojejevictor/on-prem-workup-pci-dss/backend:latest
    container_name: workup-api
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      KEYCLOAK_ISSUER_URL: ${KEYCLOAK_ISSUER_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
      CORS_ORIGINS: ${CORS_ORIGINS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: workup-api-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
      image: grafana/alloy:latest
      container_name: workup-api-alloy
      restart: unless-stopped
      volumes:
        - ./alloy-config.river:/etc/alloy/config.alloy:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/log/audit:/var/log/audit:ro
        - /var/log/journal:/var/log/journal:ro
        - /run/log/journal:/run/log/journal:ro
        - /etc/machine-id:/etc/machine-id:ro
        - /var/log/aide:/var/log/aide:ro
      command: run /etc/alloy/config.alloy
      environment:
        CF_ACCESS_CLIENT_ID: ${CF_ACCESS_CLIENT_ID}
        CF_ACCESS_CLIENT_SECRET: ${CF_ACCESS_CLIENT_SECRET}
      depends_on:
        - api

volumes:
  postgres-data: