all:
  children:
    frontend: 
      hosts:
        frontend-01: # we can add multiple hosts for frontend, if we're scaling
          ansible_host: 192.168.123.21
    auth:
      hosts:
        auth_01:
          ansible_host: 192.168.123.22
    backend:
      hosts:
        backend_01:
          ansible_host: 192.168.123.23
    observability:
      hosts:
        observability_01:
          ansible_host: 192.168.123.24
