---
- name: Ensure auditd is installed
  ansible.builtin.apt:
    name: auditd
    state: present

- name: Deploy PCI audit rules
  ansible.builtin.copy:
    src: files/pci-audit.rules   
    dest: /etc/audit/rules.d/pci-dss.rules
    owner: root
    group: root
    mode: "0640"
  notify: Reload auditd rules

- name: Ensure auditd is enabled and running
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    state: started

- name: Ensure audit log directory permissions (10.3.1 / 10.3.2)
  ansible.builtin.file:
    path: /var/log/audit
    owner: root
    group: root
    mode: "0750"
    state: directory
